project_id = "invbnyxieoyohahqhbir"

[functions.temp-track]
verify_jwt = false

[functions.connect-driver]
verify_jwt = false

[functions.notify-inactivity]
verify_jwt = false

[functions.pod-otp]
verify_jwt = false

[functions.sos-dispatch]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-paystack-checkout]
verify_jwt = false

[functions.sos-create]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.trial-reminder]
verify_jwt = false

[functions.geofence-email]
verify_jwt = false

[functions.bulk-email]
verify_jwt = false
